import {
  ClerkLoading,
  SignInButton,
  SignOutButton,
  useUser,
} from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Home: NextPage = () => {
  const { user, isLoaded, isSignedIn } = useUser();
  const router = useRouter();

  // Redirect with useEffect to actual page vs...
  useEffect(() => {
    if (isLoaded && !isSignedIn) {
      void router.replace("/sign-in");
    }
  });
  console.log(user);
  //   if (!isLoaded) {
  //     return <ClerkLoading />;
  //   }

  return (
    <>
      {isLoaded && user && (
        <>
          <Head>
            <title>Clerk Example App</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className="flex min-h-screen flex-col items-center justify-center bg-white">
            <div>
              {/* ...Display button with a ternary*/}
              {/* {!isSignedIn && <SignInButton />} */}
              <SignOutButton />
            </div>
          </main>
        </>
      )}
    </>
  );
};

export default Home;
